name = "SpaceIndices"
uuid = "5a540a4e-639f-452a-b107-23ea09ed4d36"
license = "MIT"
desc = "A package to fetch and parse space indices."
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "1.2.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
OptionalData = "fbd9d27c-2d1c-5c1c-99f2-7497d746985d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
OptionalData = "1"
Reexport = "1"
Scratch = "1"
julia = "1.6"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"


[targets]
test = ["Test", "Logging", "ForwardDiff", "ReverseDiff", "Zygote"]
